services:
  leeio_mysql:
    image: mariadb:10.9.3
    volumes:
      - mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - ./.dbenv
    ports:
      - 3306:3306
  leeio_app:
    image: leeio
    build: .
    restart: unless-stopped
    volumes:
      - ./leeio_data/config.yaml:/app/config.yaml
      - ./leeio_data/GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
    depends_on:
      - leeio_mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - 8090:80
    environment:
      - PMA_HOST=leeio_mysql
    depends_on:
      - leeio_mysql
volumes:
  mysql:
